# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-13 22:31
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationcate',
            options={'verbose_name': '应用领域', 'verbose_name_plural': '应用领域'},
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': '代理品牌', 'verbose_name_plural': '代理品牌'},
        ),
        migrations.AlterField(
            model_name='applicationcate',
            name='describe',
            field=models.TextField(max_length=511, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='applicationcate',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='分类ID(限英文字母)'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='describe',
            field=models.CharField(max_length=255, verbose_name='品牌描述'),
        ),
        migrations.AlterField(
            model_name='news',
            name='context',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='新闻内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='describe',
            field=models.TextField(max_length=255, verbose_name='新闻描述'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, upload_to='img/%Y/%m', verbose_name='首页大图'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='新闻标题'),
        ),
        migrations.AlterField(
            model_name='productmaincate',
            name='describe',
            field=models.TextField(max_length=511, verbose_name='类别介绍'),
        ),
        migrations.AlterField(
            model_name='productmaincate',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='产品分类ID(限英文字母)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='describe',
            field=models.TextField(max_length=511, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productSecondCate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ProductSecondCate', verbose_name='产品细化分类'),
        ),
        migrations.AlterField(
            model_name='productsecondcate',
            name='describe',
            field=models.TextField(max_length=511, verbose_name='类别介绍'),
        ),
        migrations.AlterField(
            model_name='productsecondcate',
            name='productMainCate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ProductMainCate', verbose_name='产品细化分类'),
        ),
    ]
